<a href="https://colab.research.google.com/github/meDOBBY21/MDSC-101/blob/main/23911-MDSC101-Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy.linalg as la
import numpy as np

In [ ]:
def display(matrix):
	print()
	for i in matrix:
		print(i)
	print()

In [ ]:
def createMatrix():
    m,n=map(int,input('Enter matrix dim:').split())

    matrix=np.empty((m,n))
    for i in range(m):
        for j in range(n):
            value = float(input(f"Enter the value for element ({i}, {j}): "))
            matrix[i, j] = value
    return matrix

In [ ]:
matrix=createMatrix()
eval,evect=la.eig(matrix)
eval,evect

Enter matrix dim: 1 1
Enter the value for element (0, 0): 1


(array([1.]), array([[1.]]))

In [ ]:
mat=createMatrix()
matT=mat.transpose()

mat,matT

Enter matrix dim:3 2
Enter the value for element (0, 0): 1
Enter the value for element (0, 1): 2
Enter the value for element (1, 0): 3
Enter the value for element (1, 1): 4
Enter the value for element (2, 0): 5
Enter the value for element (2, 1): 6


(array([[1., 2.],
        [3., 4.],
        [5., 6.]]),
 array([[1., 3., 5.],
        [2., 4., 6.]]))

#U


In [ ]:
temp=mat@matT
e1,U=la.eig(temp)
for i,e in enumerate(e1):
    e1[i]=round(e,8)
e1,U


(array([90.73549491,  0.26450509,  0.        ]),
 array([[-0.2298477 , -0.88346102,  0.40824829],
        [-0.52474482, -0.24078249, -0.81649658],
        [-0.81964194,  0.40189603,  0.40824829]]))

#V

In [ ]:
temp=matT@mat
e2,V=la.eig(temp)
for i,e in enumerate(e2):
    e2[i]=round(e,8)
e2,V

(array([ 0.26450509, 90.73549491]),
 array([[-0.78489445, -0.61962948],
        [ 0.61962948, -0.78489445]]))

In [ ]:
L=np.zeros(mat.shape)
i=0
for ele in e1:
    if ele in e2:
        L[i,i]=np.sqrt(ele)
        i+=1
L

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [ ]:
A=U@L@V.T
A

array([[ 2., -1.],
       [ 4., -3.],
       [ 6., -5.]])